# Generated by Django 2.2.2 on 2020-05-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasbooking', '0002_newconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='newconnection',
            name='cost',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
