# Generated by Django 2.2.2 on 2020-05-24 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasbooking', '0003_newconnection_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookcylinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gassize', models.CharField(max_length=100, null=True)),
                ('booknumber', models.CharField(max_length=100, null=True)),
                ('bookdate', models.CharField(max_length=100, null=True)),
                ('bookstatus', models.CharField(max_length=100, null=True)),
                ('reffercost', models.CharField(max_length=100, null=True)),
                ('assignto', models.CharField(max_length=100, null=True)),
                ('responsetime', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gasbooking.Registration')),
            ],
        ),
    ]
