# Generated by Django 2.2.2 on 2020-05-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasbooking', '0006_addstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcylinder',
            name='assignto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gasbooking.Addstaff'),
        ),
    ]
