# Generated by Django 2.2.2 on 2020-05-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasbooking', '0007_auto_20200525_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcylinder',
            name='assignto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
